'use client'

import React, { useState } from 'react';
import '../styles/styles.scss';
import '../../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import Navbar from '../components/Navbar'
import '../../node_modules/bootstrap/dist/js/bootstrap.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

  const [theme, setTheme] = useState('light'); // Inicialmente establece el tema en 'dark'

  const toggleTheme = () => {
    if (theme === 'dark') {
      setTheme('light');
    } else {
      setTheme('dark');
    }
  };

  return (
    <html lang="en" data-bs-theme={theme}>
      <body>

        <Navbar toggleTheme={toggleTheme} theme={theme} />

        {children}

      </body>
    </html>
  );
}
